info:
  contact: {}
paths:
  /ping:
    get:
      description: Simple ping endpoint
      produces:
      - text/plain
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: Ping
      tags:
      - System
swagger: "2.0"
