// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: car.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const carExists = `-- name: CarExists :one
SELECT EXISTS (
    SELECT 1
    FROM cars
    WHERE id = $1
)
`

func (q *Queries) CarExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, carExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countCars = `-- name: CountCars :one
SELECT COUNT(*)
FROM cars
`

func (q *Queries) CountCars(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCars)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCar = `-- name: CreateCar :one
INSERT INTO cars (
    id,
    brand,
    model,
    production_year,
    color,
    price,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, brand, model, production_year, color, price, created_at, updated_at
`

type CreateCarParams struct {
	ID             uuid.UUID          `json:"id"`
	Brand          string             `json:"brand"`
	Model          string             `json:"model"`
	ProductionYear int16              `json:"production_year"`
	Color          string             `json:"color"`
	Price          pgtype.Numeric     `json:"price"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateCar(ctx context.Context, arg CreateCarParams) (Car, error) {
	row := q.db.QueryRow(ctx, createCar,
		arg.ID,
		arg.Brand,
		arg.Model,
		arg.ProductionYear,
		arg.Color,
		arg.Price,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Car
	err := row.Scan(
		&i.ID,
		&i.Brand,
		&i.Model,
		&i.ProductionYear,
		&i.Color,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCar = `-- name: DeleteCar :exec
DELETE FROM cars
WHERE id = $1
`

func (q *Queries) DeleteCar(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCar, id)
	return err
}

const getCarByID = `-- name: GetCarByID :one
SELECT
    id,
    brand,
    model,
    production_year,
    color,
    price,
    created_at,
    updated_at
FROM cars
WHERE id = $1
`

func (q *Queries) GetCarByID(ctx context.Context, id uuid.UUID) (Car, error) {
	row := q.db.QueryRow(ctx, getCarByID, id)
	var i Car
	err := row.Scan(
		&i.ID,
		&i.Brand,
		&i.Model,
		&i.ProductionYear,
		&i.Color,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCars = `-- name: ListCars :many
SELECT id, brand, model, production_year, color, price, created_at, updated_at
FROM cars
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListCarsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCars(ctx context.Context, arg ListCarsParams) ([]Car, error) {
	rows, err := q.db.Query(ctx, listCars, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Car{}
	for rows.Next() {
		var i Car
		if err := rows.Scan(
			&i.ID,
			&i.Brand,
			&i.Model,
			&i.ProductionYear,
			&i.Color,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCar = `-- name: UpdateCar :one
UPDATE cars
SET
    brand = $2,
    model = $3,
    production_year = $4,
    color = $5,
    price = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING id, brand, model, production_year, color, price, created_at, updated_at
`

type UpdateCarParams struct {
	ID             uuid.UUID      `json:"id"`
	Brand          string         `json:"brand"`
	Model          string         `json:"model"`
	ProductionYear int16          `json:"production_year"`
	Color          string         `json:"color"`
	Price          pgtype.Numeric `json:"price"`
}

func (q *Queries) UpdateCar(ctx context.Context, arg UpdateCarParams) (Car, error) {
	row := q.db.QueryRow(ctx, updateCar,
		arg.ID,
		arg.Brand,
		arg.Model,
		arg.ProductionYear,
		arg.Color,
		arg.Price,
	)
	var i Car
	err := row.Scan(
		&i.ID,
		&i.Brand,
		&i.Model,
		&i.ProductionYear,
		&i.Color,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
