// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: car.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countFilteredCars = `-- name: CountFilteredCars :one
SELECT COUNT(*)
FROM cars
WHERE (
    $1::text = ''
    OR STRPOS(LOWER(brand), LOWER($1::text)) > 0
    OR STRPOS(LOWER(model), LOWER($1::text)) > 0
    OR STRPOS(LOWER(CONCAT_WS(' ', brand, model)), LOWER($1::text)) > 0
)
AND ($2::smallint IS NULL OR production_year = $2::smallint)
AND ($3::timestamptz IS NULL OR created_at >= $3::timestamptz)
AND ($4::timestamptz IS NULL OR created_at <= $4::timestamptz)
AND ($5::numeric IS NULL OR price >= $5::numeric)
AND ($6::numeric IS NULL OR price <= $6::numeric)
`

type CountFilteredCarsParams struct {
	Name        string             `json:"name"`
	Year        pgtype.Int2        `json:"year"`
	CreatedFrom pgtype.Timestamptz `json:"created_from"`
	CreatedTo   pgtype.Timestamptz `json:"created_to"`
	MinPrice    pgtype.Numeric     `json:"min_price"`
	MaxPrice    pgtype.Numeric     `json:"max_price"`
}

func (q *Queries) CountFilteredCars(ctx context.Context, arg CountFilteredCarsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFilteredCars,
		arg.Name,
		arg.Year,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.MinPrice,
		arg.MaxPrice,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCar = `-- name: CreateCar :one
INSERT INTO cars (
    id,
    brand,
    model,
    production_year,
    color,
    price,
    created_at,
    updated_at,
    image,
    model_generation,
    description
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING id, brand, model, production_year, color, price, created_at, updated_at, image, model_generation, description
`

type CreateCarParams struct {
	ID              uuid.UUID          `json:"id"`
	Brand           string             `json:"brand"`
	Model           string             `json:"model"`
	ProductionYear  int16              `json:"production_year"`
	Color           string             `json:"color"`
	Price           pgtype.Numeric     `json:"price"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Image           pgtype.Text        `json:"image"`
	ModelGeneration pgtype.Text        `json:"model_generation"`
	Description     pgtype.Text        `json:"description"`
}

func (q *Queries) CreateCar(ctx context.Context, arg CreateCarParams) (Car, error) {
	row := q.db.QueryRow(ctx, createCar,
		arg.ID,
		arg.Brand,
		arg.Model,
		arg.ProductionYear,
		arg.Color,
		arg.Price,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Image,
		arg.ModelGeneration,
		arg.Description,
	)
	var i Car
	err := row.Scan(
		&i.ID,
		&i.Brand,
		&i.Model,
		&i.ProductionYear,
		&i.Color,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Image,
		&i.ModelGeneration,
		&i.Description,
	)
	return i, err
}

const deleteCar = `-- name: DeleteCar :exec
DELETE FROM cars
WHERE id = $1
`

func (q *Queries) DeleteCar(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCar, id)
	return err
}

const filterCars = `-- name: FilterCars :many
SELECT id, brand, model, production_year, color, price, created_at, updated_at, image, model_generation, description
FROM cars
WHERE (
    $1::text = ''
    OR STRPOS(LOWER(brand), LOWER($1::text)) > 0
    OR STRPOS(LOWER(model), LOWER($1::text)) > 0
    OR STRPOS(LOWER(CONCAT_WS(' ', brand, model)), LOWER($1::text)) > 0
)
AND ($2::smallint IS NULL OR production_year = $2::smallint)
AND ($3::timestamptz IS NULL OR created_at >= $3::timestamptz)
AND ($4::timestamptz IS NULL OR created_at <= $4::timestamptz)
AND ($5::numeric IS NULL OR price >= $5::numeric)
AND ($6::numeric IS NULL OR price <= $6::numeric)
ORDER BY created_at DESC
LIMIT $8 OFFSET $7
`

type FilterCarsParams struct {
	Name        string             `json:"name"`
	Year        pgtype.Int2        `json:"year"`
	CreatedFrom pgtype.Timestamptz `json:"created_from"`
	CreatedTo   pgtype.Timestamptz `json:"created_to"`
	MinPrice    pgtype.Numeric     `json:"min_price"`
	MaxPrice    pgtype.Numeric     `json:"max_price"`
	OffsetCount int32              `json:"offset_count"`
	LimitCount  int32              `json:"limit_count"`
}

func (q *Queries) FilterCars(ctx context.Context, arg FilterCarsParams) ([]Car, error) {
	rows, err := q.db.Query(ctx, filterCars,
		arg.Name,
		arg.Year,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.MinPrice,
		arg.MaxPrice,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Car{}
	for rows.Next() {
		var i Car
		if err := rows.Scan(
			&i.ID,
			&i.Brand,
			&i.Model,
			&i.ProductionYear,
			&i.Color,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Image,
			&i.ModelGeneration,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCarByID = `-- name: GetCarByID :one
SELECT
    id,
    brand,
    model,
    production_year,
    color,
    price,
    created_at,
    updated_at,
    image,
    model_generation,
    description
FROM cars
WHERE id = $1
`

func (q *Queries) GetCarByID(ctx context.Context, id uuid.UUID) (Car, error) {
	row := q.db.QueryRow(ctx, getCarByID, id)
	var i Car
	err := row.Scan(
		&i.ID,
		&i.Brand,
		&i.Model,
		&i.ProductionYear,
		&i.Color,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Image,
		&i.ModelGeneration,
		&i.Description,
	)
	return i, err
}

const updateCar = `-- name: UpdateCar :one
UPDATE cars
SET
    brand = $2,
    model = $3,
    production_year = $4,
    color = $5,
    price = $6,
    image = CASE WHEN $7::boolean THEN $8::text ELSE image END,
    model_generation = CASE WHEN $9::boolean THEN $10::text ELSE model_generation END,
    description = CASE WHEN $11::boolean THEN $12::text ELSE description END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, brand, model, production_year, color, price, created_at, updated_at, image, model_generation, description
`

type UpdateCarParams struct {
	ID                 uuid.UUID      `json:"id"`
	Brand              string         `json:"brand"`
	Model              string         `json:"model"`
	ProductionYear     int16          `json:"production_year"`
	Color              string         `json:"color"`
	Price              pgtype.Numeric `json:"price"`
	SetImage           bool           `json:"set_image"`
	Image              pgtype.Text    `json:"image"`
	SetModelGeneration bool           `json:"set_model_generation"`
	ModelGeneration    pgtype.Text    `json:"model_generation"`
	SetDescription     bool           `json:"set_description"`
	Description        pgtype.Text    `json:"description"`
}

func (q *Queries) UpdateCar(ctx context.Context, arg UpdateCarParams) (Car, error) {
	row := q.db.QueryRow(ctx, updateCar,
		arg.ID,
		arg.Brand,
		arg.Model,
		arg.ProductionYear,
		arg.Color,
		arg.Price,
		arg.SetImage,
		arg.Image,
		arg.SetModelGeneration,
		arg.ModelGeneration,
		arg.SetDescription,
		arg.Description,
	)
	var i Car
	err := row.Scan(
		&i.ID,
		&i.Brand,
		&i.Model,
		&i.ProductionYear,
		&i.Color,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Image,
		&i.ModelGeneration,
		&i.Description,
	)
	return i, err
}
