// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Car struct {
	ID             uuid.UUID          `json:"id"`
	Brand          string             `json:"brand"`
	Model          string             `json:"model"`
	ProductionYear int16              `json:"production_year"`
	Color          string             `json:"color"`
	Price          pgtype.Numeric     `json:"price"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
